---

- hosts: all
  become: true
  tasks:

    - name: Install the apache2 and php packages for Ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php  
        state: latest
        update_cache: yes
      when: ansible_distribution_version == "Debian"     

